General cleanup with shellcheck and shfmt for bashrc and profile

diff --git a/shell/bashrc b/shell/bashrc
--- a/shell/bashrc
+++ b/shell/bashrc
@@ -23,8 +23,8 @@ shopt -s hostcomplete   # Attempts hostname completion when @ is present in a st
 # ----------- #
 # Completions #
 # ----------- #
-if [ -f /etc/bash_completion ]; then
-	. /etc/bash_completion
+if [[ -f /etc/bash_completion ]]; then
+  . /etc/bash_completion
 fi
 
 # ----------------- #
@@ -46,15 +46,15 @@ bind "set vi-cmd-mode-string \001\033[1;33m\002[COMMAND] \001\033[0m\002"
 PROMPT_DIRTRIM=2
 
 function parseVenv() {
-	if [ -n "$venv" ]; then
-		echo -e "\001\033[1;34m\002(\001\033[1;36m\002$venv\001\033[1;34m\002) "
-	fi
+  if [[ -n "${venv}" ]]; then
+    echo -e "\001\033[1;34m\002(\001\033[1;36m\002${venv}\001\033[1;34m\002) "
+  fi
 }
 
 function parseMambaEnv() {
-	if [ -n "$CONDA_DEFAULT_ENV" ]; then
-		echo -e "\001\033[1;34m\002(\001\033[1;36m\002$CONDA_DEFAULT_ENV\001\033[1;34m\002) "
-	fi
+  if [[ -n "${CONDA_DEFAULT_ENV}" ]]; then
+    echo -e "\001\033[1;34m\002(\001\033[1;36m\002${CONDA_DEFAULT_ENV}\001\033[1;34m\002) "
+  fi
 }
 
 PS1='\001\033[1;34m\002[\001\033[1;37m\002\t\001\033[1;34m\002] $(parseVenv)$(parseMambaEnv)\001\033[0m\002\u\001\033[1;34m\002@\001\033[0m\002\h\n\001\033[1;37m\002\w\001\033[0m\002 '
@@ -64,27 +64,27 @@ PS4='+${BASH_SOURCE[0]##*/}($LINENO)/${FUNCNAME[0]}> '
 # --------- #
 # ENV Setup #
 # --------- #
-export XDG_CACHE_HOME="$HOME/.cache"
-export XDG_CONFIG_HOME="$HOME/.config"
-export XDG_DATA_HOME="$HOME/.local/share"
-export XDG_STATE_HOME="$HOME/.local/state"
-export XDG_DOCUMENTS_DIR="$HOME/Documents"
+export XDG_CACHE_HOME="${HOME}/.cache"
+export XDG_CONFIG_HOME="${HOME}/.config"
+export XDG_DATA_HOME="${HOME}/.local/share"
+export XDG_STATE_HOME="${HOME}/.local/state"
+export XDG_DOCUMENTS_DIR="${HOME}/Documents"
 
 export TMPDIR="/tmp"
 
 if nvim --version >/dev/null 2>&1; then
-	export EDITOR="nvim"
+  export EDITOR="nvim"
 elif vim --version >/dev/null 2>&1; then
-	export EDITOR="vim"
+  export EDITOR="vim"
 elif vi --version >/dev/null 2>&1; then
-	export EDITOR="vi"
+  export EDITOR="vi"
 elif nano --version >/dev/null 2>&1; then
-	export EDITOR="nano"
+  export EDITOR="nano"
 else
-	echo "WARNING: EDITOR could not be set." >&2
+  echo "WARNING: EDITOR could not be set." >&2
 fi
-if [ -n "$EDITOR" ]; then
-	export VISUAL="$EDITOR"
+if [[ -n "${EDITOR}" ]]; then
+  export VISUAL="${EDITOR}"
 fi
 
 export LANG="en_US.UTF-8"
@@ -93,37 +93,36 @@ export LANG="en_US.UTF-8"
 declare -a repository_directories
 repository_directories=("${HOME}/repositories" "${XDG_DOCUMENTS_DIR}/repositories")
 for path in "${repository_directories[@]}"; do
-	[[ -d "${path}" ]] && export REPOSITORY_DIR="${path}" && break
+  [[ -d "${path}" ]] && export REPOSITORY_DIR="${path}" && break
 done
 
-export MAMBA_EXE="$HOME/.src/miniforge3/bin/mamba"
-export MAMBA_ROOT_PREFIX="$HOME/.src/miniforge3"
+export MAMBA_EXE="${HOME}/.src/miniforge3/bin/mamba"
+export MAMBA_ROOT_PREFIX="${HOME}/.src/miniforge3"
 
 # ------------------ #
 # Navigation Helpers #
 # ------------------ #
-if [ -f "$REPOSITORY_DIR/directory-explorer/directory-explorer.sh" ]; then
-	. "$REPOSITORY_DIR/directory-explorer/directory-explorer.sh"
+if [[ -f "${REPOSITORY_DIR}/directory-explorer/directory-explorer.sh" ]]; then
+  . "${REPOSITORY_DIR}/directory-explorer/directory-explorer.sh"
 fi
 
 # ------- #
 # Aliases #
 # ------- #
-if [ -e "$HOME"/.bash_aliases ]; then
-	. "$HOME/.bash_aliases"
+if [[ -e "${HOME}"/.bash_aliases ]]; then
+  . "${HOME}/.bash_aliases"
 fi
 
 # ----- #
 # Mamba #
 # ----- #
-if [ -f "$MAMBA_EXE" ]; then
-	__mamba_setup="$("$MAMBA_EXE" shell hook --shell bash --root-prefix "$MAMBA_ROOT_PREFIX" 2>/dev/null)"
-	if [ $? -eq 0 ]; then
-		eval "$__mamba_setup"
-	else
-		alias mamba="$MAMBA_EXE"
-	fi
-	unset __mamba_setup
+if [[ -f "${MAMBA_EXE}" ]]; then
+  if __mamba_setup="$("${MAMBA_EXE}" shell hook --shell bash --root-prefix "${MAMBA_ROOT_PREFIX}" 2>/dev/null)"; then
+    eval "${__mamba_setup}"
+  else
+    alias mamba='${MAMBA_EXE}'
+  fi
+  unset __mamba_setup
 fi
 
 # --------------------------------- #
@@ -133,7 +132,7 @@ fi
 declare -a user_executable_paths
 user_executable_paths=("${HOME}/bin" "${HOME}/.bin" "${HOME}/.local/bin")
 for path in "${user_executable_paths[@]}"; do
-	[[ -d "${path}" ]] && export PATH="${path}:${PATH}"
+  [[ -d "${path}" ]] && export PATH="${path}:${PATH}"
 done
 
 # --------------------- #
